name: benchmark-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - mlflow== 2.4.1
    - azureml-mlflow==1.51.0
    - azureml-core==1.53.0
    - psutil>=5.8,<5.9
    - ipykernel~=6.0
    - u8darts[all]
